Feature/toxic log removal
kiwicampus/realsense-ros pull request #11
Opened 2021-07-27 21:39 UTC by pepisg

In this PR I removed the toxic logs from staging and production applications
` No stream match for pointcloud chosen texture Process - Color`

2021-07-30 21:26 UTC, charlielito requested changes
I don't like this logic inside this code.  For example if the applications names change this brakes.
This should be an env vars for just enablind the logging, and in Kronos we set that env variable depending the application

2021-08-02 16:37 UTC, pepisg commented
What do you think about this new implementation @charlielito ?

2021-08-02 17:28 UTC, charlielito requested changes
This looks good. Nevertheless I'll recommend to add this new env var as a parameter of the node, like the other parameters that this node already has, so you don't need to implement that `getEnv` function and this could just be passed in the launch file like the other parameters

2021-08-02 17:28 UTC, charlielito commented on realsense2_camera/include/base_realsense_node.h
> +        bool _display_logs=true;
maybe a better name like `_texture_display_logs`

2021-08-02 22:47 UTC, charlielito approved these changes
Remove that comment

2021-08-02 22:47 UTC, charlielito commented on realsense2_camera/src/base_realsense_node.cpp
> +    ROS_INFO_STREAM("Texture logs displaying: " << _camera_link_z);
?

2021-08-02 22:52 UTC, merged